-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "zhCN")
if not L then return end

L["Add Handy Note"] = "添加标记"
L["Add this location to Cartographer_Waypoints"] = "将这个位置添加到Cartographer_Waypoints插件去"
L["Add this location to TomTom waypoints"] = "将这个位置添加到TomTom插件去"
--[==[ L[ [=[
Alt+Right Click To Add a HandyNote]=] ] = [=[
Alt+Right Click To Add a HandyNote]=] ]==]
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00提示：|cffeda55fCtrl+Shift+左键拖拽|cFF00FF00可以移动一个标记"
L["Configuration for each individual plugin database."] = "配置每个独立的数据插件"
L["Delete Handy Note"] = "删除标记"
L["Description/Notes:"] = "说明/注释："
L["Edit Handy Note"] = "编辑标记"
L["Enable HandyNotes"] = "启用HandyNotes"
L["Enable or disable HandyNotes"] = "启用或者禁用HandyNotes"
L["ERROR_CREATE_NOTE1"] = "HandyNotes cannot create a note here as it is unable to obtain your current location. Usually this is because there is no map for the zone you are in."
L["HandyNotes"] = "HandyNotes"
L["Icon Alpha"] = "图标透明度"
L["Icon Scale"] = "图标缩放"
L["Minimap Icon Alpha"] = "小地图图标透明度"
L["Minimap Icon Scale"] = "小地图图标缩放"
-- L["(No Title)"] = "(No Title)"
L["Overall settings"] = "全局设置"
L["Overall settings that affect every database"] = "作用于所有数据库的全局设置"
L["Plugin databases"] = "数据插件"
L["Plugins"] = "插件"
-- L["Portal"] = "Portal"
L["Show on continent map"] = "在大陆地图上显示"
-- L["Show the following plugins on the map"] = "Show the following plugins on the map"
-- L["Syntax:"] = "Syntax:"
L["The alpha transparency of the icons"] = "图标的透明度"
L["The overall alpha transparency of the icons on the Minimap"] = "小地图上图标的全局透明度值"
L["The overall alpha transparency of the icons on the World Map"] = "世界地图上图标的全局透明度值"
L["The overall scale of the icons on the Minimap"] = "小地图上图标的全局缩放值"
L["The overall scale of the icons on the World Map"] = "世界地图上图标的全局缩放值"
L["The scale of the icons"] = "图标的缩放值"
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "这些设置可以全局控制HandyNotes的外观及风格。这里的图标的缩放和透明度会乘以插件的缩放及透明度。"
L["These settings control the look and feel of the HandyNotes icons."] = "这些设置控制HandyNotes图标的外观及风格。"
L["Title"] = "标题"
L["World Map Icon Alpha"] = "世界地图图标透明度"
L["World Map Icon Scale"] = "世界地图图标缩放"

